### ISSUE TITLE
Make tld `.dev` configurable

### ISSUE THREAD

**Issue by gnufied** [code-mancers/invoker#101]
There is a chance that `.dev` can be made globally available TLD, in which case using `.dev` for local development may not be viable, so I think we should aim to make TLD configurable so as developers can locally configure it.

**Comment by gnufied** [comment]
This has become a priority now because `.dev` is a real TLD down and hence conflicts with other domains. We should get configurable TLD done.

**Comment by nisanth074** [comment]
@gnufied Something like?

```
tld = local

[redis]
command = redis-server /usr/local/etc/redis.conf

[memcached]
command = /usr/local/opt/memcached/bin/memcached
```

**Comment by gnufied** [comment]
@nisanth074 I don't think that will work.

The TLD setup has to be part of `invoker setup` command and written once to invoker configuration file. the `.ini` file you shown is user written per project config file. 

So something like `invoker setup --tld local`

**Comment by nisanth074** [comment]
Working on a pull request here https://github.com/code-mancers/invoker/pull/153

**Comment by homeworkprod** [comment]
FTR, while accessing Invoker-provided `.dev` domains in Firefox works fine for me, Chromium 48.0 blocks it, stating:

> This webpage is not available
>
> ERR_ICANN_NAME_COLLISION
>
> This site is using a new generic top-level domain (gTLD). […]

**Comment by kgrz** [comment]
This is complete, I think.
