### ISSUE TITLE
Proxy websockets

### ISSUE THREAD

**Issue by swrobel** [code-mancers/invoker#110]
It would be great to be able to proxy secure websockets (wss://) to insecure websocket servers (ws://) the same way that invoker does https to http proxying. An example application of this is livereload servers, which all still seem to only support insecure websockets.

**Comment by gnufied** [comment]
Fixed in master. @swrobel  if you don't mind building a invoker gem from master perhaps worth giving a try.

**Comment by swrobel** [comment]
:clap: works perfectly! :bomb:

**Comment by iffyuva** [comment]
@swrobel worth writing steps which you followed, and how you tested it. might be helpful for others :)

**Comment by swrobel** [comment]
@iffyuva I'm absolutely planning on writing it up. Right now it's forks of rack-livereload and guard-livereload hacked together to make it work, but when I have a formula that works well, I'll post. Thanks again for adding this feature!
