### ISSUE TITLE
Add support for groups

### ISSUE THREAD

**Issue by Darksecond** [code-mancers/invoker#118]
It would be nice to have group support. So a number of processes can be managed at the same time.

**Comment by iffyuva** [comment]
this is pretty nice idea!

**Comment by nisanth074** [comment]
To support groups, `invoker.ini` can look something like

```
[db:postgres]
command = /usr/local/Cellar/postgresql/9.3.5_1/bin/postgres -D /usr/local/var/postgres

[db:redis]
command = redis-server /usr/local/etc/redis.conf

[resque]
command = bundle exec rake resque:work
```

To stop both postgres and redis, use

```
invoker stop db 
```

**Comment by iffyuva** [comment]
is it a good idea to add attribute "group" here instead of playing with alias of process?

eg:
```
[postgres]
command = /usr/local/Cellar/postgresql/9.3.5_1/bin/postgres -D /usr/local/var/postgres
group = db

[redis]
command = redis-server /usr/local/etc/redis.conf
group = db

[resque]
command = bundle exec rake resque:work
```
we can save some parsing headaches i guess.

**Comment by gnufied** [comment]
Yeah, I suppose using separate group names is better.  Lets go with that.

**Comment by nisanth074** [comment]
Opened a pull here https://github.com/code-mancers/invoker/pull/138
