### ISSUE TITLE
Simpler usage instructions when using rvm

### ISSUE THREAD

**Issue by nisanth074** [code-mancers/invoker#119]
Not sure if running
```
rvmsudo invoker setup
```
makes the invoker binary available always, when using rvm
```
nisanth074@nisanth074:~$ rvm current
ruby-2.2.0
nisanth074@nisanth074:~$ which invoker
/home/nisanth074/.rvm/gems/ruby-2.2.0/bin/invoker
nisanth074@nisanth074:~$ rvm use 1.9.3
Using /home/nisanth074/.rvm/gems/ruby-1.9.3-p551
nisanth074@nisanth074:~$ which invoker
```

A simpler way to is take advantage of `rvm do` command and add an alias
```bash
# in ~/.bashrc
alias invoker='NOEXEC_DISABLE=1 rvm default do invoker'
```

I plan to update the usage instructions with rvm. Thoughts?

**Comment by iffyuva** [comment]
i generally install invoker everytime i install a new ruby version. let me try approach and get back to you.

**Comment by iffyuva** [comment]
im okie with adding this usage instruction to docs as a suggestion.

**Comment by iffyuva** [comment]
btw, running `rvmsudo invoker setup` is used to setup firewall rules and stuff. this command and the statement "makes the invoker binary available always" are not related.

my workflow with rvm and invoker is this:

```
# if i require 2.1.5, i do
$ rvm install 2.1.5
$ rvm use --default 2.1.5

# now if i have to install 2.2.0
$ rvm install 2.2.0
$ rvm use --default 2.2.0
```

so, i always set latest version as default. as a result, if i have to use `rvm default do invoker` im forced to install invoker everytime i install a new ruby version as my default always changes. as a result i have invoker with all rubies that i have installed :) so i don't have to use `rvm <version> do`

**Comment by nisanth074** [comment]
Thanks for sharing your workflow. The line "makes the invoker binary available always" was misleading. I'll add the alias as a suggestion
```
alias invoker='NOEXEC_DISABLE=1 rvm <ruby_version_with_invoker_installed> do invoker'
```
