### ISSUE TITLE
docs: move github ribbon to more prominent location

### ISSUE THREAD

**Issue by iffyuva** [code-mancers/invoker#120]
![gh](https://cloud.githubusercontent.com/assets/1108398/6332313/838c6fca-bbaa-11e4-943a-0df3c1ab1092.png)

extensions often pop up at bottom left corner. i think its better to move this ribbon out of bottom left corner.

**Comment by gnufied** [comment]
Fixed by https://github.com/code-mancers/invoker/commit/0a7bba45a96801bcc093cb9f4f3a279d5816548b
