### ISSUE TITLE
Add support for proxying based on URI path

### ISSUE THREAD

**Issue by dlee** [code-mancers/invoker#121]
It would be useful if invoker proxied based on URI path as well as domain.

For example:
`app.dev` => app
`app.dev/search` => search
`app.dev/chat` => chat

**Comment by dlee** [comment]
The ini could look like this:
```ini
[rails]
directory = /Users/bob/rails/
command = rails s -p $PORT

[search]
directory = /Users/bob/search/
command = searchd -p $PORT
path_prefix = /search

[chat]
directory = /Users/bob/chat/
command = chatd -p $PORT
path_prefix = /chat
```

**Comment by gnufied** [comment]
Hmm, it is def. doable. @dlee if you can open a PR I will be happy to merge. otherwise it is bit lower in my own feature list priority for next release.

**Comment by dlee** [comment]
Fixed by https://github.com/code-mancers/invoker/pull/123
