### ISSUE TITLE
Shared env vars for all apps launched by invoker

### ISSUE THREAD

**Issue by dlee** [code-mancers/invoker#124]
It's common practice to share config files or secrets via env vars.

It would be nice to be able to set env vars that would be automatically sent to all commands launched by invoker.

**Comment by gnufied** [comment]
Invoker supports per project `.env` loading although there is no global environment variable loading.

**Comment by gnufied** [comment]
@dlee can you elaborate more? As I said already - Invoker supports `.env` loading.

**Comment by dlee** [comment]
Hi, sorry I missed this.


By env var, I meant shell environment variable, so that if you run:
```
ABC=123 XYZ=456 CONFIG_FILE=/etc/blah invoker somecommand
```
Then you get access to $ABC, $XYZ, and $CONFIG_FILE from within invoker.

**Comment by dlee** [comment]
BTW, it seems like invoker already supports this, so I'm not sure why I filed this in the first place. Sorry for the confusion.
