### ISSUE TITLE
Add support for spring?

### ISSUE THREAD

**Issue by gnufied** [code-mancers/invoker#13]
I am thinking invoker should support spring (https://github.com/jonleighton/spring). I have not worked out details yet but I am thinking of a flag in config file which will enable invoker to start spring server on each supported application.

**Comment by halilim** [comment]
Unfortunately, yeah. Related [documentation](https://github.com/rails/spring#rails-console-rails-generate-rails-runner):
> ... If you run a different sub command (e.g. rails server) then spring will automatically pass it through to the underlying rails executable (without the speed-up).

**Comment by iffyuva** [comment]
@swrobel @halilim thanks for the update.
@gnufied i think this issue can be closed.

**Comment by iffyuva** [comment]
closing this one. lets revisit if spring supports `rails server`.
