### ISSUE TITLE
Stdout not always being captured

### ISSUE THREAD

**Issue by ysimonson** [code-mancers/invoker#135]
The stdout of child processes isn't always captured (namely, for node.js processes.) The result is that not all stdout is wrapped with the colorful logging.

On the node.js side, I've tried to use both `console.log` and `process.stdout.write`. Both have this effect.

It appears that `Reactor::Reader.process_read` isn't even getting the data. Any idea what would cause this?

**Comment by nisanth074** [comment]
@ysimonson Is this still happening? If so, I'll try replicating the issue on my machine.

**Comment by ysimonson** [comment]
Yes, still happening with the newest stable version of invoker

**Comment by gnufied** [comment]
Can you post a sample application that reproduces this problem?

**Comment by ysimonson** [comment]
Sorry, I wish I could, but we moved off of invoker - so unable to reproduce at this point. Will close.
