### ISSUE TITLE
Invoker domains do not work on 10.11 El Capitan

### ISSUE THREAD

**Issue by chrismanderson** [code-mancers/invoker#139]
Seems like Invoker `1.3.2` domains do not work in 10.11 - ran invoker setup, and things seemed like they were set up properly, but cannot hit any domain with the .dev extension. I can hit the sites directly by IP.

Obviously, 10.11 is early beta, just posting this as a heads up.

**Comment by gnufied** [comment]
We will look into this as soon as we near El Capitan release. Thank you for alerting us.

**Comment by iffyuva** [comment]
@chrismanderson i upgraded to 10.11 from 10.10, and invoker works on 10.11. can you please explain the issue that you are facing or help me in reproducing this bug? thanks.

**Comment by R167** [comment]
I have been getting similar problems:
`/Users/wmd/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/invoker-1.3.2/lib/invoker/power/powerup.rb:12: warning: epoll is not supported on this platform`
Have tried multiple reinstalls.

**Comment by iffyuva** [comment]
i doubt if this issue is related to eventmachine again. what i have observed is: when invoker tries to connect to any of backend using em-proxy, its throwing `Errno::ECONNREFUSED` error. investigating more into this.

**Comment by iffyuva** [comment]
@chrismanderson @R167 your issue might be related to #154 please make sure that your servers are not running in ipv6 mode.

to test this on osx, please run this command:

```sh
 lsof -iTCP -sTCP:LISTEN -P
```

and make sure that type is IPv4. thanks to @emilsoman for pointing this out :)

**Comment by iffyuva** [comment]
im closing this issue, please re-open this issue if the problem still persists.
