### ISSUE TITLE
rinetd creating huge log files

### ISSUE THREAD

**Issue by kgrz** [code-mancers/invoker#142]
I've installed invoker on a remote ubuntu Digital ocean server on 15th July 2015. Ran the `setup` for the gem and left it as it is. When I checked on 21st July 2015, the instance reported that it was out of disk space (~20GB droplet). Turns out that the culprit is a `rinet` related log file that got nearly 15GB. Note that I haven't started invoker on a project at any point in these 7 days.

This probably is a user level setting (log rotation, rinet configuration etc.), but I was thinking this should be mentioned somewhere in the linux setup instructions as a sidenote.

**Comment by datashaman** [comment]
For those running linux and have rinetd installed, watch out. It has recently become buggy. 100% CPU usage and massive logging of an error. I found a 60G log file today. Debian have patched it, but it will take a while for that to filter down.

http://osdir.com/ml/general/2016-01/msg17015.html

**Comment by gnufied** [comment]
I have pushed a fix that replaces rinetd with socat - https://github.com/code-mancers/invoker/pull/160

If you want, you can try pulling this branch and building and installing a gem yourself. Of course you will have to remove rinted first and most likely all invoker setup files too.

**Comment by gnufied** [comment]
Fixed with #160
