### ISSUE TITLE
Support LinuxMint

### ISSUE THREAD

**Issue by PragTob** [code-mancers/invoker#143]
It'd be great if LinuxMint were supported, it is one of the most popular distros. I get `Your selected distro is not supported by Invoker (RuntimeError)`.

As Linux Mint is based on Ubuntu (14.04 currently) it should be easy and mainly just do what Ubuntu does.

I did a temporary local fix with:

```ruby
          case Facter[:operatingsystem].value
          when "Ubuntu", "LinuxMint"
            require "invoker/power/setup/distro/ubuntu"
            Ubuntu.new
```

which seemed to work fine :)

**Comment by iffyuva** [comment]
hi @PragTob would you like to open a PR? will be more than happy to merge it :)

**Comment by PragTob** [comment]
Sure thing :) Will do.

**Comment by Krishna-akkala** [comment]
Hi, i am running invoker setup --tld testsite from centos7 command prompt. but unfortunately i am facing the below error. 
`/usr/local/share/gems/gems/facter-2.5.1/lib/facter/core/execution/posix.rb:9: warning: Insecure world writable dir /root/.nvm/v9.4.0/bin in PATH, mode 040777
/usr/local/share/gems/gems/invoker-1.5.6/lib/invoker/power/setup/distro/base.rb:35:in `distro_installer': Your selected distro is not supported by Invoker (RuntimeError)
	from /usr/local/share/gems/gems/invoker-1.5.6/lib/invoker/power/setup/linux_setup.rb:59:in `initialize_distro_installer'
	from /usr/local/share/gems/gems/invoker-1.5.6/lib/invoker/power/setup/linux_setup.rb:13:in `setup_invoker'
	from /usr/local/share/gems/gems/invoker-1.5.6/lib/invoker/power/setup.rb:37:in `install'
	from /usr/local/share/gems/gems/invoker-1.5.6/lib/invoker/power/setup.rb:10:in `install'
	from /usr/local/share/gems/gems/invoker-1.5.6/lib/invoker/cli.rb:20:in `setup'
	from /usr/local/share/gems/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/share/gems/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/share/gems/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/share/gems/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /usr/local/share/gems/gems/invoker-1.5.6/lib/invoker/cli.rb:12:in `start'
	from /usr/local/share/gems/gems/invoker-1.5.6/bin/invoker:7:in `<top (required)>'
	from /usr/local/bin/invoker:23:in `load'
	from /usr/local/bin/invoker:23:in `<main>'`

can anyone please help me in resolving this issue?
