### ISSUE TITLE
Non-STDOUT logs?

### ISSUE THREAD

**Issue by swanandp** [code-mancers/invoker#155]
Is there a way to tell invoker to watch the log for a process in a certain location?

Like, say: 

```ini
[sidekiq]
directory = /Users/swanand/code/apps/awesome-app
log = /Users/swanand/code/apps/awesome-app/log/sidekiq.log
command = bundle exec sidekiq -c 5 -L log/sidekiq.log
```

**Comment by nisanth074** [comment]
@swanandp Thanks for the feature suggestion. There isn't a builtin feature to watch file logs yet.

It might be possible to do this currently with the `tail` command. In your invoker.ini, try adding
```ini
[sidekiq_log]
directory = /Users/swanand/code/apps/awesome-app/log
command = tail -f sidekiq.log
```

**Comment by gnufied** [comment]
yeah an external command to tail a log would work. Not sure if you would want that though. :P

**Comment by nisanth074** [comment]
@gnufied Yea. Its more like a temporary workaround :)

Any thoughts on how the configuration should look like? May be something like
```ini
[sidekiq]
directory = /Users/swanand/code/apps/awesome-app
command = bundle exec sidekiq -c 5 -L log/sidekiq.log
tail = /Users/swanand/code/apps/awesome-app/log/sidekiq.log
tail = /Users/swanand/code/apps/awesome-app/log/anothersidekiqlog.log
```
or
```ini
[sidekiq]
directory = /Users/swanand/code/apps/awesome-app
command = bundle exec sidekiq -c 5 -L log/sidekiq.log
tail_log = /Users/swanand/code/apps/awesome-app/log/sidekiq.log
tail_log = /Users/swanand/code/apps/awesome-app/log/anothersidekiqlog.log
```

**Comment by gnufied** [comment]
I am not sure about having this as a builtin feature of Invoker. Lately, I have come to realization that most applications should write to `STDOUT` by default. 

It has several benefits. such as:
1. such applications can run inside containers easily.
2. external tools like scribe or logrotate can easily do something with those logs. In other words, any external tool can easily do something with your logs if you are writing them to STDOUT.

**Comment by swanandp** [comment]
Alright.
