### ISSUE TITLE
Invoker does not pass on SIGINT to child processes

### ISSUE THREAD

**Issue by swanandp** [code-mancers/invoker#157]
Sending `SIGINT` ( `Ctrl+C`ing ) invoker should kill all the processes started by invoker, however this isn't so right now. 

Best example for this is `sidekiq`; if you have a `sidekiq` process along with say, `rails` and you `SIGINT` invoker, then a `sidekiq` zombie process lingers on.  To cleanly exit all processes, `invoker remove sidekiq` is needed before sending `SIGINT` to invoker.

**Comment by gnufied** [comment]
This is really weird one. I have pushed a fix that uses same code when you run `invoker remove sidekiq` vs when you stop invoker by pressing Control-C. If you see any errors logged in console when you press `ctrl-c` can you paste it here @swanandp ?

Cheers

**Comment by gnufied** [comment]
https://github.com/code-mancers/invoker/commit/ea59cbdc4c1258cec7d1778ced6f7c0d9e387872 <-- fix btw. You may have to pull and build gem locally though

**Comment by swanandp** [comment]
Thanks for the fix! No errors on the terminal that I can see, by the way.

**Comment by gnufied** [comment]
So the fix does not fixes the problem?

**Comment by swanandp** [comment]
So yes, upgrading to latest version did solve this issue. I had actually stopped using Invoker for a period of time because of this problem. Thanks for solving!

**Comment by gnufied** [comment]
Cheers. New version 1.5.1 is out - let us know if you find anything else. thanks @swanandp  :D
