### ISSUE TITLE
Release new version of gem

### ISSUE THREAD

**Issue by parisyee** [code-mancers/invoker#166]
Hi,

Would it be possible to cut a new release of the gem? We're especially interested in the updated [process manager](https://github.com/code-mancers/invoker/commit/ea59cbdc4c1258cec7d1778ced6f7c0d9e387872).

cc/ @rupurt

**Comment by gnufied** [comment]
Can anyone try v1.5.0 which I tagged? I am thinking of release this as new version of the gem. Let me know, if you run into any problems.

Documentation needs to be updated with new features before the release as well, so I am trying to get that done before final release.

**Comment by iffyuva** [comment]
ive been using #1b05c71 for sometime, no issues so far!

**Comment by gnufied** [comment]
Cool. A new version has been published.
