### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by swrobel** [code-mancers/invoker#172]
It would be nice to have one, preferably in markdown format. Thanks for the gem!

http://keepachangelog.com/

**Comment by gnufied** [comment]
That is a good idea. I will make sure this happens. :-)

**Comment by swrobel** [comment]
Any update? There's been a release since this discussion.

**Comment by gnufied** [comment]
Added - https://github.com/code-mancers/invoker/pull/191

sorry that 1.5.3 went without a changelog but hopefully, we can keep this straight going ahead.
