### ISSUE TITLE
Heroku Procfile not spawning the rails app properly (incorrect directory?)

### ISSUE THREAD

**Issue by timotei** [code-mancers/invoker#177]
Hi,

I have a rails app, using it via the `testapp.dev` domain and I previously used `invoker.ini` to run it:

```
[testapp]
directory = .
command = bash -lc "rvm `cat .ruby-version`@`cat .ruby-gemset` do bundle exec rails s -p $PORT"
```

I have recently migrated to `Procfile` to use it with heroku, and I have the following `Procfile`:

```
web: bundle exec rails server -p $PORT
worker: rake jobs:work
```

However, now, the app is not served anymore apparently, and I get the following error when I'm visiting the top-level domain `testapp.dev`. However, accessing the app via its port works.

```
Application not found
Invoker could not find the application. Please check the configuration file.
```

Now, I tried re-setting it up (`sudo invoker setup`) with only the `Procfile`, but still same result. What's interesting is that the directory seems to not be the right one when using `Procfile`.

This is the result of `invoker list` when using `invoker.ini`:

```
$ invoker list                   
  +-------------------------------+-------+------+--------------+---------------------------------------------+
  | dir                           | pid   | port | process_name | shell_command                               |
  +-------------------------------+-------+------+--------------+---------------------------------------------+
  | /Users/user/src/testapp       | 13646 | 9000 | testapp      | bash -lc "rvm `cat .ruby-version`@`cat .r.. |
  +-------------------------------+-------+------+--------------+---------------------------------------------+
```

and this is when using `Procfile`:

```
$ invoker list                         
  +-----+-------+------+--------------+----------------------------------+
  | dir | pid   | port | process_name | shell_command                    |
  +-----+-------+------+--------------+----------------------------------+
  |     | 14380 | 9000 | web          | bundle exec rails server -p 9000 |
  |     | 14381 |      | worker       | rake jobs:work                   |
  +-----+-------+------+--------------+----------------------------------+
```

Even if I set the command to `web: cd /Users/user/src/testapp && bundle exec rails server -p $PORT` it still doesn't properly work.

Am I missing something or is there a bug? (which I can try and fix)

Thanks

**Comment by gotoAndBliss** [comment]
Any luck @timotei ?

**Comment by gnufied** [comment]
Since you migrated to `Procfile` your app label is called `web`. So you need to access the application on `http://web.dev`.  That should work.
