### ISSUE TITLE
Incompatible with Ruby 2.4

### ISSUE THREAD

**Issue by mrfoto** [code-mancers/invoker#182]
Maybe I'm doing something wrong but I've tried everything I thought of and it's still the exact same error. I've reinstalled ruby, I've reinstalled all my gems, but no matter what I do, this is what I get:
```
dyld: lazy symbol binding failed: Symbol not found: _rb_data_object_wrap
  Referenced from: /Users/mrfoto/.gem/ruby/2.4.0/gems/http-parser-lite-0.6.0/ext/http-parser/http_parser.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_data_object_wrap
  Referenced from: /Users/mrfoto/.gem/ruby/2.4.0/gems/http-parser-lite-0.6.0/ext/http-parser/http_parser.bundle
  Expected in: flat namespace


Process with command powerup_manager exited with status
```

I get this by running `invoker start` and then opening `http://joinrun.dev/ and my invoker.ini is very simple:
```
[joinrun]
command = bundle exec rails s -p $PORT

[sidekiq]
command = bundle exec sidekiq -C config/sidekiq.yml
```

The app runs just fine if I run it without invoker.

**Comment by gnufied** [comment]
Is there by any chance you have multiple ruby environments present and ruby version `X` is trying to load compiled extensions for some other version? I tried this on a fresh ubuntu box I built via vagrant and I did not have any trouble starting invoker.

@iffyuva can you verify as well mate?

**Comment by mrfoto** [comment]
I have multiple ruby environments and I manage them with `chruby`. The gems are installed in the correct path `~/.gem/ruby/2.4.0/` 😕

**Comment by mrfoto** [comment]
Huh, I moved all the old rubies out of `.rubies` folder and it started to work. Maybe it's a `chruby` issue, I never even thought that could be it.

Sorry, and thank you!

**Comment by gnufied** [comment]
No problem.

**Comment by iffyuva** [comment]
@gnufied or @nisanth074 please cut a release as it has been quite sometime. Thanks.

**Comment by jeromedalbert** [comment]
I am having the same problem with ruby 2.4 but using rbenv.

> Is there by any chance you have multiple ruby environments present and ruby version X is trying to load compiled extensions for some other version? 

How can I know that?
