### ISSUE TITLE
[Feature request] `invoker list` with watch mode

### ISSUE THREAD

**Issue by adis-io** [code-mancers/invoker#200]
I'd like to see `invoker list` with watch/follow mode.

Is it hard to do? I thought I can try to implement, but with your help.

**Comment by gnufied** [comment]
If you want watch mode, you can simply run `invoker list` with watch command. i.e - `watch invoker list`. That should display status of processes as they start/die etc.

**Comment by adisos** [comment]
Yeah, I knew it. Actually I'm doing it now. But I think it would be cool if it was achieved with IPC.
