### ISSUE TITLE
Change the default .dev tld to .test (or other)

### ISSUE THREAD

**Issue by jeromedalbert** [code-mancers/invoker#205]
My Chrome browser updated to version 63 today. It forces .dev domains to HTTPS, with preloaded HSTS.

In practice it means that `.dev` domains don't work. Even when using https, I cannot ignore invalid dev certificates any more:

<img width="1392" alt="screen shot 2017-12-15 at 3 00 58 pm" src="https://user-images.githubusercontent.com/236461/34063890-f1c99f30-e1a9-11e7-852a-b4502c052e82.png">

No more "proceed to website (unsafe)" option. This has a huge impact for all devs using `.dev` domains. `.dev` is not suitable for development any more.

For now you can work around the problem by using a different domain: `sudo invoker setup --tld test`.

Anyways, a new domain, for example `.test`, should replace `.dev` as the default domain. FYI, Pow uses `.test`.

For reference:
- https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/
- https://github.com/basecamp/pow/pull/547
- https://github.com/puma/puma-dev/issues/139

**Comment by kgrz** [comment]
I'm liking `.localhost` more. Downside is higher number of chars :(

**Comment by iffyuva** [comment]
You can re-install with `--tld` option https://github.com/code-mancers/invoker/pull/153/files. Please refer to `.dev TLD support for OSX and Linux` section in docs http://invoker.codemancers.com/

**Comment by kgrz** [comment]
https://github.com/code-mancers/invoker/pull/206 Changed default domain `.local` because I like it and it's shorter than `.localhost`, and a bit more specific than `.test`. Should we maintain compat with pow and use `.test` instead?

**Comment by jeromedalbert** [comment]
`dev` was perfect because it had only 3 letters to type, and I can't think of a meaningful replacement with 3 letters. The next word with 4 letters is `.test`, which is shorter to type. `.local` is 5 letters but is a better description.

Eventually it would be nice if there was a consensus on Pow, Invoker, and Puma-dev. Would make switching between each other easier. Maybe we maintain compat with pow and use `.test`, or we ask Pow to change to `.local`, which is arguably more descriptive?

**Comment by shir** [comment]
Looks like `.local` is bad option. At least for Mac OS X. It doesn't work as expected. For example see this discussion https://discussions.apple.com/thread/7707202

**Comment by gnufied** [comment]
@kgrz @iffyuva I think I agree, it appears that `.local` might not be best choice. it conflicts with avahi on Linux too (https://unix.stackexchange.com/questions/352237/avahi-daemon-and-local-domain-issues).

I propose `.devel` as invoker's TLD. I know it is 5 letter but ain't worse than `.local` which was 5 letter too and `.devel` is unlikely to be used by another component on Linux or OSX.

**Comment by shir** [comment]
@gnufied according to [this RFC](https://tools.ietf.org/html/rfc2606#section-2) only next domains are available for internal usage: `.test`, `.example`, `.invalid`, `.localhost`

Looks like `.test` or `.localhost` are best options which will not break anything. And user always may set something different if he want.

**Comment by kgrz** [comment]
Cool, will push a change to `.test` tonight. My bad that I didn't do much research while changing this. Sorry :(
