### ISSUE TITLE
Invoker with Ubuntu 18.04

### ISSUE THREAD

**Issue by meneerprins** [code-mancers/invoker#219]
Hi, I'm trying to use Invoker with a fresh 18.04 Ubuntu installation but I can't get it to work. When I run `sudo invoker setup --tld test` I keep getting an error: `failed to create listening socket for port 53: Address already in use` I tried to find a solution but nothing really worked and I'm not an Ubuntu expert so modifying system files without knowing what I'm doing seems like a bad idea for me. Anyone that knows a solution?

**Comment by gnufied** [comment]
BTW it is possible that you are running into conflicts between `systemd-resolved` and `dnsmasq`. In which case suggested workaround appears to be:

https://unix.stackexchange.com/questions/304050/how-to-avoid-conflicts-between-dnsmasq-and-systemd-resolved?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
