### ISSUE TITLE
Invoker not working correctly with rbenv

### ISSUE THREAD

**Issue by tomchapin** [code-mancers/invoker#29]
Here's the command given in the documentation that doesn't seem to be working:

```
command = RBENV_VERSION=2.0.0-p0 zsh -c "bundle exec rails s"
```

Here's my invoker ini file:

```
[rails4example]
directory = /Users/tchapin/Documents/dev/rails4example
port = 3001
command = RBENV_VERSION=2.0.0-p0 zsh -c "bundle exec rails s"
```

Here's what happens when I try to run invoker:

```
rails4example : Gemfile syntax error:
rails4example : /Users/tchapin/Documents/dev/rails4example/Gemfile:48: syntax error, unexpected ':', expecting kEND
rails4example :   gem 'sdoc', require: false
rails4example :
```

When I alter my invoker ini to run this command instead:

```
command = RBENV_VERSION=2.0.0-p0 zsh -c "ruby --version"
```

I get this result:

```
rails4example : ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]
```

It appears that invoker is launching the zsh instance in some sort of manner that is skipping all of the initialization and path settings in my ~/.zshrc file, and as a result, everything is being executed as if I don't even have rbenv installed and it's just trying to use the default ruby that's installed on OSX by default.

Any idea how to make this work correctly?

**Comment by kek** [comment]
The suggestion by @gnuified doesn't work anymore. I have tried it and I'm still getting

`login : Your Ruby version is 2.1.3, but your Gemfile specified 2.1.5`

zsh 5.0.5 (x86_64-apple-darwin14.0)
rbenv 0.4.0-98-g13a474c

**Comment by kek** [comment]
This worked:

`command = RBENV_VERSION=2.1.5 bash -c 'rbenv exec bundle exec rails s'`
