### ISSUE TITLE
Allow processes that are `inactive` by default

### ISSUE THREAD

**Issue by scsmith** [code-mancers/invoker#67]
It would be nice to allow processes to be added to the ini file that don't load automatically when you call `invoker start my.ini`.

You could then call `invoker start processname` to make the process load when you actually need it.

Alternatively @gnufied suggested it might be possible to make it load automatically when it's called by the URL. So calling http://processname.dev would force a start for an inactive process.

Thoughts?

**Comment by gnufied** [comment]
For now we have added support for flag `disable_autorun=true` in `.ini` file to disable autostarting of processes. We will look into adding support for autostarting processes via url as part of https://github.com/code-mancers/invoker/issues/122
