### ISSUE TITLE
Document remote-pry usage with Invoker

### ISSUE THREAD

**Issue by gnufied** [code-mancers/invoker#88]

**Comment by gnufied** [comment]
Fixed with https://github.com/code-mancers/invoker/commit/e1a0f3ff3ff079c0e293de0a7090955efac06ed5

**Comment by etherbob** [comment]
This no longer works with newer ruby/rails/invoker

One work around is to run rails separately and then use invoker add_http _appname_ _port_

It'd be nice to have an option to somehow do this from the invoker config, but I'm not sure
